### ISSUE TITLE
should probably explicitly clear the backbuffer?

### ISSUE THREAD

**Issue by RamKromberg** [ax-va/PyOpenGL-Pygame-Stemkoski-Pascale-2021#4]
I've only just started browsing through the book but I've had a rendering issue with the first few examples where the previous back buffer leaks into the current run. It goes as follows:
1. ``python example-2-11.py`` correctly renders just the red triangle and lets me move it around.
2. close the window.
3. immediately follow with ``python example-2-01.py`` renders the red triangle.
4. alternatively, running ``python example-2-03.py`` will have the the red triangle "peak" behind the yellow hexagon.
5. you can also have the early examples leak into each other. like, running 1 after 3 will render the hexagon...

This mostly works with the first 5 examples after running other examples, watching videos, playing games... Basically, anything that only flips the back buffer once. 11 (and probably the following examples) don't seem to show this issue since, I'm assuming, the animation flips the buffer at least twice so it clears up.

Anyhow, it's probably specific to non-compositing wm (I'm running i3wm...), but I figured it's worth mentioning.

Regards

**Comment by ax-va** [comment]
Hi,
thanks for the feedback. I don't have the problems you described. I think your GPU is not clearing the color buffer automatically. Try adding to these examples:
```
import OpenGL.GL as GL
```
and then in the `update` method at the very beginning
```
GL.glClearColor(0, 0, 0, 1)
GL.glClear(GL.GL_COLOR_BUFFER_BIT | GL.GL_DEPTH_BUFFER_BIT)
```

The first command sets the default color (here black) and the second one clears the color buffer to the default color and also the depth buffer. If it still does not work, try replacing 
```
GL.glClear(GL.GL_COLOR_BUFFER_BIT | GL.GL_DEPTH_BUFFER_BIT)
```
by only 
```
GL.glClear(GL.GL_COLOR_BUFFER_BIT)
```

In the other examples, you do not have this problem, because the Renderer object does this for you. 
Best regards, Alex

**Comment by RamKromberg** [comment]
yeah that did the trick. Both ``GL.glClear(GL.GL_COLOR_BUFFER_BIT | GL.GL_DEPTH_BUFFER_BIT)`` and ``GL.glClear(GL.GL_COLOR_BUFFER_BIT)`` cleared things up. I also tested the different clears in both ``update`` and ``initialize`` and either way works fine.

For reference:
```
pygame 2.1.2 (SDL 2.0.20, Python 3.9.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Vendor: AMD
Renderer: AMD Radeon RX 550 Series (polaris11, LLVM 13.0.1, DRM 3.42, 5.15.43)
OpenGL version supported: 4.6 (Compatibility Profile) Mesa 22.0.2
GLSL version supported: 4.60
Initializing program...
```

Thanks.
